name: HTML CI Pipeline

on:
    push:
        branches: [main]

jobs:
    build-and-validate:
        runs-on: debian-latest


        steps:
            - name: Clone code
              uses: actions/checkout@v3


            - name: Build Docker image
              run: docker build -t static-html .


            - name: HTML validate
              run: | 
                sudo apt-get ipdate && sudo apt-get install -y tidy
                tidy -e index.html || true